name: django
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python manage.py test